
- hosts: localhost
  connection: local
#  become: yes
  roles:
     - osp-network
     - osp-keypair
     - osp-securitygroup
     - osp-flavor

  tasks:

  - name: import instance_details
    include_vars: instance_vars.yml

    ##Create Instances
  - name: "Create instances using instance_details"
    include_role:
      name: osp-instances
      public: true

## Alternate Method to create dynmaic inventory
  - name: Gather facts
    include_role: 
       name: osp-facts
    tags:
     - test_inventory
