---
# tasks file for roles/win_ad_user
- name: Create windows domain group
  win_domain_group:
    state:  present
    name:   "{{ item.group_name }}"
    scope:  "{{ item.group_scope }}"
  loop:     "{{ user_info }}"

- name: Create AD Users
  win_domain_user:
    state:     present
    name:      "{{ item.name }}"
    firstname: "{{ item.firstname }}"
    surname:   "{{ item.surname }}"
    password:  "{{ item.password }}"
    groups:    "{{ item.group_name }}"
    email:    '"{{ item.name }}"@ad1."{{ GUID }}".example.opentlc.com'
  loop:       "{{ user_info }}"
