---
- name: Simple in-memory from an AWS region
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Gather EC2 facts
      ec2_instance_facts:
        profile:        "{{ aws_profile | default('gpte') }}"
        region:         "{{ aws_region_final | default(aws_region) | default(region) | default('us-east-1') }}"
        filters:
          "tag:guid": "{{ guid }}"
      register: r_ec2_facts
      tags:
        - must

    - name: Print inventory
      debug:
        var: ec2_facts
        verbosity: 2

    - when: host.state.name != 'terminated'
      name: Generate inventory
      add_host:
        name:                           "{{ host.tags.internaldns | default(item.private_dns_name) }}"
        shortname:                      "{{ host.tags.Name | default(item.private_dns_name) }}"
        ansible_user:                   ec2-user
        remote_user:                    ec2-user
        ansible_ssh_private_key_file:   "{{ host['key_name'] }}"
        key_name:                       "{{ host['key_name'] }}"
        state:                          "{{ host['state'] }}"
        internaldns:                    "{{ host.tags.internaldns | default(item.private_dns_name) }}"
        isolated:                       "{{ host.tags.isolated | default(false) }}"
        instance_id:                    "{{ host.instance_id }}"
        region:                         "{{ aws_region_final | default(aws_region) | default(region) | default('us-east-1') }}"
        public_dns_name:                "{{ host['public_dns_name'] }}"
        private_dns_name:               "{{ host['private_dns_name'] }}"
        private_ip_address:             "{{ host['private_ip_address'] }}"
        public_ip_address:              "{{ host['public_ip_address'] }}"
        placement:                      "{{ host['placement']['availability_zone'] }}"
        image_id:                       "{{ host['image_id'] }}"
        ansible_ssh_extra_args:         "-o StrictHostKeyChecking=no"
        bastion:                        "{{ local_bastion | default('') }}"
      loop:         "{{ r_ec2_facts['instances'] }}"
      loop_control:
        label:      "{{ host.tags.internaldns | default(item.private_dns_name) }}"
        loop_var: host
      tags:
        - must


    - name: Print inventory
      debug:
        msg:
          - "name {{ host.tags.internaldns | default(item.private_dns_name) }}"
        verbosity: 2
      loop: "{{ r_ec2_facts['instances'] }}"
      loop_control:
        label: "{{ host.tags.internaldns | default(item.private_dns_name) }}"
        loop_var: host

